---
AWSTemplateFormatVersion: '2010-09-09'
Description: Auto Scaling Group with Launch Configuration
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where the instances will launch
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets for launching EC2 instances
  ImageId:
    Type: AWS::EC2::Image::Id
    Description: AMI ID for the EC2 instances
  InstanceType:
    Type: String
    Default: t3.medium
    AllowedValues:
    - t2.micro
    - t2.small
    - t3.micro
    - t3.medium
    - t3.large
    Description: EC2 instance type
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group for EC2 instances
Resources:
  LaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId:
        Ref: ImageId
      InstanceType:
        Ref: InstanceType
      SecurityGroups:
      - Ref: SecurityGroupId
      InstanceMonitoring: true
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        Ref: Subnets
      LaunchConfigurationName:
        Ref: LaunchConfig
      MinSize: '1'
      MaxSize: '3'
      DesiredCapacity: '2'
      Tags:
      - Key: Name
        Value: ASG-Instance
        PropagateAtLaunch: true
