format_version: 10
pipelines:
  launch-asg-pipeline:
    group: cloudformation
    label_template: "${COUNT}"
    materials:
      git:
        url: git@github.com:ananyasinha0125/ananya.git
        branch: main
    stages:
      - name: generate-asg
        jobs:
          - name: launch-asg
            resources:
              - cfn-ready
            tasks:
              - script: |

                  aws cloudformation deploy \
                    --template-file launch-config.yaml \
                    --stack-name ASGviaLC \
                    --parameter-overrides $(cat launch-config.json | jq -r '.[] | "\(.ParameterKey)=\(.ParameterValue)"' | xargs) \
                    --capabilities CAPABILITY_NAMED_IAM



